### 🌳 '타이타닉호 탑승자' 데이터셋 입니다.
### 빈 칸(♥)을 채워 데이터 전처리를 진행해보세요!

**✔️ [파일] - [Drive에 사본 저장]**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files # 구글 코랩 라이브러리에 있는 'files 모듈'을 사용하기 위한 명령어
files.upload() # 'files' 모듈의 upload()를 실행 → '파일 선택'버튼 활성화
df = pd.read_csv('Titanic.csv', encoding='utf-8') # file1.csv를 데이터프레임 형태로 읽고 변수 df에 할당

Saving Titanic.csv.csv to Titanic.csv (2).csv

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.shape

(891, 12)

# **🗨️ [문제1] 결측치 유무 파악하기**

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

이상치 유무 파악하기

In [ ]:
import numpy as np
def outliers_iqr(dt, col):
    q1, q3 = np.percentile(dt[col], [25, 75])
    iqr = q3 - q1
    outlier_bottom = q1 - (1.5 * iqr)
    outlier_top = q3 + (1.5 * iqr)
    outliers_1 = dt[col] < outlier_bottom
    outliers_2 = dt[col] > outlier_top
    outliers = dt[outliers_1 | outliers_2]
    return outliers[[col]]
find_outliers = outliers_iqr(df, 'Fare')
find_outliers

         Fare
1     71.2833
27   263.0000
31   146.5208
34    82.1708
52    76.7292
..        ...
846   69.5500
849   89.1042
856  164.8667
863   69.5500
879   83.1583

[116 rows x 1 columns]

# **🗨️ [문제2] 불필요한 데이터 속성 삭제하기**

In [ ]:
df_core_columns = df.drop(['PassengerId', 'Name', 'Ticket'], axis = 1)

# **🗨️ [문제3] 데이터의 결측치가 많은 ‘Cabin’ 속성을 제거하기**

In [ ]:
df_notnull = df_core_columns.drop(['Cabin'], axis = 1)

# **🗨️ [문제4] 결측치가 있는 데이터 제거**

In [ ]:
df_notnull = df_notnull.dropna()

### ⭐ 이상치가 있는 데이터를 치환하기

# **🗨️ [문제5] 'Fare' 속성의 이상치를 결측치로 변경하고 확인**

In [ ]:
find_outliers = outliers_iqr(df_notnull, 'Fare')
df_notnull.loc[find_outliers.index, 'Fare'] = np.nan
df_notnull.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age          0
SibSp        0
Parch        0
Fare        95
Embarked     0
dtype: int64

## **🗨️ [문제6] 이상치 치환하기**
(이상치 → 결측치로 변경 후 평균값으로 치환)

In [ ]:
mean_Fare = df_notnull['Fare'].mean(axis = 0)
df_notnull['Fare'].fillna(df_notnull['Fare'].mean(), inplace = True)
df_notnull.loc[find_outliers.index, 'Fare']

데이터 전처리 완료된 파일 저장하기

In [ ]:
df_notnull.to_csv('/content/Titanic2.csv')