# **🌳 국가통계포털에서 제공하는 '소비자물가지수' 데이터셋 입니다.**

🌱 각 단계에 맞추어 '**김밥의 소비자 물가 지수를 예측하는 모델**'을 제작해보세요.

✔️ 소비자물가지수? 각 가정에서 구입하는 생필품과 서비스의 가격 변동을 알아보기 위해 작성하는 통계

✔️ **[파일] - [Drive에 사본 저장]**

# **[단계1] 데이터 수집 및 불러오기**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
files.upload()

Saving consumer price index.csv to consumer price index.csv

{'consumer price index.csv': b'"\xec\x8b\x9c\xeb\x8f\x84\xeb\xb3\x84","\xec\x8b\x9c\xec\xa0\x90",\xec\xb4\x9d\xec\xa7\x80\xec\x88\x98,\xeb\x86\x8d\xec\xb6\x95\xec\x88\x98\xec\x82\xb0\xeb\xac\xbc,(\xeb\x86\x8d\xec\x82\xb0\xeb\xac\xbc)\xea\xb3\xa1\xeb\xac\xbc,\xec\x8c\x80,\xed\x98\x84\xeb\xaf\xb8,\xec\xb0\xb9\xec\x8c\x80,\xeb\xb3\xb4\xeb\xa6\xac\xec\x8c\x80,\xec\xbd\xa9,\xeb\x95\x85\xec\xbd\xa9,\xed\x98\xbc\xec\x8b\x9d\xea\xb3\xa1,(\xeb\x86\x8d\xec\x82\xb0\xeb\xac\xbc)\xec\xb1\x84\xec\x86\x8c,\xeb\xb0\xb0\xec\xb6\x94,\xec\x83\x81\xec\xb6\x94,\xec\x8b\x9c\xea\xb8\x88\xec\xb9\x98,\xec\x96\x91\xeb\xb0\xb0\xec\xb6\x94,\xeb\xaf\xb8\xeb\x82\x98\xeb\xa6\xac,\xea\xb9\xbb\xec\x9e\x8e,\xeb\xb6\x80\xec\xb6\x94,\xeb\xac\xb4,\xec\x97\xb4\xeb\xac\xb4,\xeb\x8b\xb9\xea\xb7\xbc,\xea\xb0\x90\xec\x9e\x90,\xea\xb3\xa0\xea\xb5\xac\xeb\xa7\x88,\xeb\x8f\x84\xeb\x9d\xbc\xec\xa7\x80,\xec\xbd\xa9\xeb\x82\x98\xeb\xac\xbc,\xeb\xb2\x84\xec\x84\xaf,\xec\x98\xa4\xec\x9d\xb4,\xed\x92\x8b\xea\xb3\xa0\xec\xb6\x94,\xed\x98\xb8\xeb\xb0\x95,\xea\xb0\x80\xec\xa7\x80,\xed\x86\xa0\xeb\xa7\x88\xed\x86\xa0,\xed\x8c\x8c,\xec\x96\x91\xed\x8c\x8c,\xeb\xa7\x88\xeb\x8a\x98,\xeb\xb8\x8c\xeb\xa1\x9c\xec\xbd\x9c\xeb\xa6\xac,\xea\xb3\xa0\xec\x82\xac\xeb\xa6\xac,\xed\x8c\x8c\xed\x94\x84\xeb\xa6\xac\xec\xb9\xb4,\xec\x83\x9d\xea\xb0\x95,(\xeb\x86\x8d\xec\x82\xb0\xeb\xac\xbc)\xea\xb3\xbc\xec\x8b\xa4,\xec\x82\xac\xea\xb3\xbc,\xeb\xb0\xb0,\xeb\xb3\xb5\xec\x88\xad\xec\x95\x84,\xed\x8f\xac\xeb\x8f\x84,\xeb\xb0\xa4,\xea\xb0\x90,\xea\xb7\xa4,\xec\x98\xa4\xeb\xa0\x8c\xec\xa7\x80,\xec\xb0\xb8\xec\x99\xb8,\xec\x88\x98\xeb\xb0\x95,\xeb\x94\xb8\xea\xb8\xb0,\xeb\xb0\x94\xeb\x82\x98\xeb\x82\x98,\xed\x82\xa4\xec\x9c\x84,\xeb\xb8\x94\xeb\xa3\xa8\xeb\xb2\xa0\xeb\xa6\xac,\xeb\xa7\x9d\xea\xb3\xa0,\xec\xb2\xb4\xeb\xa6\xac,\xec\x95\x84\xeb\xb3\xb4\xec\xb9\xb4\xeb\x8f\x84,\xed\x8c\x8c\xec\x9d\xb8\xec\x95\xa0\xed\x94\x8c,\xec\x95\x84\xeb\xaa\xac\xeb\x93\x9c,(\xeb\x86\x8d\xec\x82\xb0\xeb\xac\xbc)\xea\xb8\xb0\xed\x83\x80\xeb\x86\x8d\xec\x82\xb0\xeb\xac\xbc,\xea\xb3\xa0\xec\xb6\xa7\xea\xb0\x80\xeb\xa3\xa8,\xec\xb0\xb8\xea\xb9\xa8,\xec\x9d\xb8\xec\x82\xbc,\xed\x99\x94\xec\xb4\x88,\xec\xb6\x95\xec\x82\xb0\xeb\xac\xbc,\xea\xb5\xad\xec\x82\xb0\xec\x87\xa0\xea\xb3\xa0\xea\xb8\xb0,\xec\x88\x98\xec\x9e\x85\xec\x87\xa0\xea\xb3\xa0\xea\xb8\xb0,\xeb\x8f\xbc\xec\xa7\x80\xea\xb3\xa0\xea\xb8\xb0,\xeb\x8b\xad\xea\xb3\xa0\xea\xb8\xb0,\xeb\x8b\xac\xea\xb1\x80,\xea\xbf\x80,\xec\x88\x98\xec\x82\xb0\xeb\xac\xbc,\xea\xb0\x88\xec\xb9\x98,\xeb\xaa\x85\xed\x83\x9c,\xec\xa1\xb0\xea\xb8\xb0,\xea\xb3\xa0\xeb\x93\xb1\xec\x96\xb4,\xec\x98\xa4\xec\xa7\x95\xec\x96\xb4,\xea\xb2\x8c,\xea\xb5\xb4,\xec\xa1\xb0\xea\xb0\x9c,\xec\xa0\x84\xeb\xb3\xb5,\xec\x83\x88\xec\x9a\xb0,\xeb\xa7\x88\xeb\xa5\xb8\xeb\xa9\xb8\xec\xb9\x98,\xeb\xa7\x88\xeb\xa5\xb8\xec\x98\xa4\xec\xa7\x95\xec\x96\xb4,\xeb\x82\x99\xec\xa7\x80,\xea\xb9\x80,\xeb\xaf\xb8\xec\x97\xad,\xea\xb3\xb5\xec\x97\x85\xec\xa0\x9c\xed\x92\x88,\xea\xb0\x80\xea\xb3\xb5\xec\x8b\x9d\xed\x92\x88,\xeb\xb0\x80\xea\xb0\x80\xeb\xa3\xa8,\xea\xb5\xad\xec\x88\x98,\xeb\x9d\xbc\xeb\xa9\xb4,\xeb\x8b\xb9\xeb\xa9\xb4,\xeb\x91\x90\xeb\xb6\x80,\xec\x8b\x9c\xeb\xa6\xac\xec\x96\xbc,\xeb\xb6\x80\xec\xb9\xa8\xea\xb0\x80\xeb\xa3\xa8,\xec\xbc\x80\xec\x9d\xb4\xed\x81\xac,\xeb\xb9\xb5,\xeb\x96\xa1,\xed\x8c\x8c\xec\x8a\xa4\xed\x83\x80\xeb\xa9\xb4,\xec\x86\x8c\xec\x8b\x9c\xec\xa7\x80,\xed\x96\x84\xeb\xb0\x8f\xeb\xb2\xa0\xec\x9d\xb4\xec\xbb\xa8,\xea\xb8\xb0\xed\x83\x80\xec\x9c\xa1\xeb\xa5\x98\xea\xb0\x80\xea\xb3\xb5\xed\x92\x88,\xec\x98\xa4\xec\xa7\x95\xec\x96\xb4\xec\xb1\x84,\xeb\xb6\x81\xec\x96\xb4\xec\xb1\x84,\xec\x96\xb4\xeb\xac\xb5,\xeb\xa7\x9b\xec\x82\xb4,\xec\x88\x98\xec\x82\xb0\xeb\xac\xbc\xed\x86\xb5\xec\xa1\xb0\xeb\xa6\xbc,\xec\xa0\x93\xea\xb0\x88,\xec\x9a\xb0\xec\x9c\xa0,\xeb\xb6\x84\xec\x9c\xa0,\xec\xb9\x98\xec\xa6\x88,\xeb\xb0\x9c\xed\x9a\xa8\xec\x9c\xa0,\xec\xb0\xb8\xea\xb8\xb0\xeb\xa6\x84,\xec\x8b\x9d\xec\x9a\xa9\xec\x9c\xa0,\xea\xb3\xbc\xec\x9d\xbc\xea\xb0\x80\xea\xb3\xb5\xed\x92\x88,\xeb\x8b\xa8\xeb\xac\xb4\xec\xa7\x80,\xeb\xa7\x9b\xea\xb9\x80,\xec\xb4\x88\xec\xbd\x9c\xeb\xa6\xbf,\xec\x82\xac\xed\x83\x95,\xea\xbb\x8c,\xec\x95\x84\xec\x9d\xb4\xec\x8a\xa4\xed\x81\xac\xeb\xa6\xbc,\xeb\xb9\x84\xec\x8a\xa4\xed\x82\xb7,\xec\x8a\xa4\xeb\x82\xb5\xea\xb3\xbc\xec\x9e\x90,\xed\x8c\x8c\xec\x9d\xb4,\xec\x84\xa4\xed\x83\x95,\xec\x9e\xbc,\xeb\xac\xbc\xec\x97\xbf,\xec\x86\x8c\xea\xb8\x88,\xea\xb0\x84\xec\x9e\xa5,\xeb\x90\x9c\xec\x9e\xa5,\xec\x96\x91\xeb\x85\x90\xec\x86\x8c\xec\x8a\xa4,\xea\xb3\xa0\xec\xb6\x94\xec\x9e\xa5,\xec\xb9\xb4\xeb\xa0\x88,\xec\x8b\x9d\xec\xb4\x88,\xeb\x93\x9c\xeb\xa0\x88\xec\x8b\xb1,\xed\x98\xbc\xed\x95\xa9\xec\xa1\xb0\xeb\xaf\xb8\xeb\xa3\x8c,\xec\x8a\xa4\xed\x94\x84,\xec\x9d\xb4\xec\x9c\xa0\xec\x8b\x9d,\xea\xb9\x80\xec\xb9\x98,\xeb\xb0\x91\xeb\xb0\x98\xec\xb0\xac,\xeb\x83\x89\xeb\x8f\x99\xec\x8b\x9d\xed\x92\x88,\xec\xa6\x89\xec\x84\x9d\xec\x8b\x9d\xed\x92\x88,\xed\x8e\xb8\xec\x9d\x98\xec\xa0\x90\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd,\xec\x82\xbc\xea\xb0\x81\xea\xb9\x80\xeb\xb0\xa5,\xec\xbb\xa4\xed\x94\xbc,\xec\xb0\xa8,\xec\xa3\xbc\xec\x8a\xa4,\xeb\x91\x90\xec\x9c\xa0,\xec\x83\x9d\xec\x88\x98,\xea\xb8\xb0\xeb\x8a\xa5\xec\x84\xb1\xec\x9d\x8c\xeb\xa3\x8c,\xed\x83\x84\xec\x82\xb0\xec\x9d\x8c\xeb\xa3\x8c,\xea\xb8\xb0\xed\x83\x80\xec\x9d\x8c\xeb\xa3\x8c,\xec\x86\x8c\xec\xa3\xbc,\xea\xb3\xbc\xec\x8b\xa4\xec\xa3\xbc,\xeb\xa7\xa5\xec\xa3\xbc,\xeb\xa7\x89\xea\xb1\xb8\xeb\xa6\xac,\xec\x96\x91\xec\xa3\xbc,\xec\x95\xbd\xec\xa3\xbc,\xed\x99\x8d\xec\x82\xbc,\xea\xb1\xb4\xea\xb0\x95\xea\xb8\xb0\xeb\x8a\xa5\xec\x8b\x9d\xed\x92\x88,\xec\x9c\xa0\xec\x82\xb0\xea\xb7\xa0,\xeb\x82\xb4\xea\xb5\xac\xec\x9e\xac,\xec\x9e\xa5\xeb\xa1\xb1,\xec\xb9\xa8\xeb\x8c\x80,\xea\xb1\xb0\xec\x8b\xa4\xec\x9e\xa5,\xec\x86\x8c\xed\x8c\x8c,\xec\xb1\x85\xec\x83\x81,\xec\x9d\x98\xec\x9e\x90,\xec\x8b\x9d\xed\x83\x81,\xec\x8b\xb1\xed\x81\xac\xeb\x8c\x80,\xec\xa0\x84\xea\xb8\xb0\xeb\xb0\xa5\xec\x86\xa5,\xea\xb0\x80\xec\x8a\xa4\xeb\xa0\x88\xec\x9d\xb8\xec\xa7\x80,\xec\xa0\x84\xec\x9e\x90\xeb\xa0\x88\xec\x9d\xb8\xec\xa7\x80,\xec\xa0\x84\xea\xb8\xb0\xeb\xa0\x88\xec\x9d\xb8\xec\xa7\x80,\xeb\x83\x89\xec\x9e\xa5\xea\xb3\xa0,\xea\xb9\x80\xec\xb9\x98\xeb\x83\x89\xec\x9e\xa5\xea\xb3\xa0,\xec\x97\x90\xec\x96\xb4\xec\xbb\xa8,\xec\x84\xa0\xed\x92\x8d\xea\xb8\xb0,\xea\xb3\xb5\xea\xb8\xb0\xec\xb2\xad\xec\xa0\x95\xea\xb8\xb0,\xec\x84\xb8\xed\x83\x81\xea\xb8\xb0,\xec\x9d\x98\xeb\xa5\x98\xea\xb1\xb4\xec\xa1\xb0\xea\xb8\xb0,\xec\x8b\x9d\xea\xb8\xb0\xec\x84\xb8\xec\xb2\x99\xea\xb8\xb0,\xec\xb2\xad\xec\x86\x8c\xea\xb8\xb0,\xec\x86\x8c\xed\x98\x95\xec\xa3\xbc\xeb\xb0\xa9\xea\xb0\x80\xec\xa0\x84,\xeb\xb3\xb4\xec\x98\xa8\xeb\xa7\xa4\xed\x8a\xb8,\xeb\xb3\xb4\xec\x9d\xbc\xeb\x9f\xac,\xec\x86\x8c\xed\x98\x95\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xec\xa4\x91\xed\x98\x95\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xeb\x8c\x80\xed\x98\x95\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xea\xb2\xbd\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xeb\x8b\xa4\xeb\xaa\xa9\xec\xa0\x81\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xec\x88\x98\xec\x9e\x85\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8,\xec\xa0\x84\xea\xb8\xb0\xeb\x8f\x99\xeb\xa0\xa5\xec\xb0\xa8,\xec\x9e\x90\xec\xa0\x84\xea\xb1\xb0,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xec\x9a\xa9\xed\x92\x88,\xeb\xb8\x94\xeb\x9e\x99\xeb\xb0\x95\xec\x8a\xa4,\xed\x9c\xb4\xeb\x8c\x80\xec\xa0\x84\xed\x99\x94\xea\xb8\xb0,TV,\xec\x98\x81\xec\x83\x81\xec\x9d\x8c\xed\x96\xa5\xea\xb8\xb0\xea\xb8\xb0,\xec\xbb\xb4\xed\x93\xa8\xed\x84\xb0,\xed\x9c\xb4\xeb\x8c\x80\xec\x9a\xa9\xeb\xa9\x80\xed\x8b\xb0\xeb\xaf\xb8\xeb\x94\x94\xec\x96\xb4\xea\xb8\xb0\xea\xb8\xb0,\xec\x95\x85\xea\xb8\xb0,\xed\x97\xac\xec\x8a\xa4\xea\xb8\xb0\xea\xb5\xac,\xeb\xa9\xb4\xeb\x8f\x84\xea\xb8\xb0,\xed\x97\xa4\xec\x96\xb4\xeb\x93\x9c\xeb\x9d\xbc\xec\x9d\xb4\xec\x96\xb4,\xec\x86\x90\xeb\xaa\xa9\xec\x8b\x9c\xea\xb3\x84,\xec\x9e\xa5\xec\x8b\xa0\xea\xb5\xac,\xec\x84\xac\xec\x9c\xa0\xec\xa0\x9c\xed\x92\x88,\xeb\x82\xa8\xec\x9e\x90\xec\x99\xb8\xec\x9d\x98,\xeb\x82\xa8\xec\x9e\x90\xec\x83\x81\xec\x9d\x98,\xeb\x82\xa8\xec\x9e\x90\xed\x95\x98\xec\x9d\x98,\xeb\x82\xa8\xec\x9e\x90\xeb\x82\xb4\xec\x9d\x98,\xec\x97\xac\xec\x9e\x90\xec\x99\xb8\xec\x9d\x98,\xec\x9b\x90\xed\x94\xbc\xec\x8a\xa4,\xec\x97\xac\xec\x9e\x90\xec\x83\x81\xec\x9d\x98,\xec\x97\xac\xec\x9e\x90\xed\x95\x98\xec\x9d\x98,\xec\x97\xac\xec\x9e\x90\xeb\x82\xb4\xec\x9d\x98,\xec\xa0\x90\xed\x8d\xbc,\xed\x8b\xb0\xec\x85\x94\xec\xb8\xa0,\xec\x8a\xa4\xec\x9b\xa8\xed\x84\xb0,\xec\xb2\xad\xeb\xb0\x94\xec\xa7\x80,\xec\x9a\xb4\xeb\x8f\x99\xeb\xb3\xb5,\xeb\x93\xb1\xec\x82\xb0\xeb\xb3\xb5,\xec\x9c\xa0\xec\x95\x84\xeb\x8f\x99\xeb\xb3\xb5,\xec\x96\x91\xeb\xa7\x90,\xeb\xaa\xa8\xec\x9e\x90,\xec\x9e\xa5\xea\xb0\x91,\xec\xb9\xa8\xea\xb5\xac,\xec\xbb\xa4\xed\x8a\xbc,\xec\xb6\x9c\xed\x8c\x90\xeb\xac\xbc,\xec\x9c\xa0\xec\x95\x84\xec\x9a\xa9\xed\x95\x99\xec\x8a\xb5\xea\xb5\x90\xec\x9e\xac,\xec\xb4\x88\xeb\x93\xb1\xed\x95\x99\xea\xb5\x90\xed\x95\x99\xec\x8a\xb5\xec\x84\x9c,\xec\xa4\x91\xed\x95\x99\xea\xb5\x90\xed\x95\x99\xec\x8a\xb5\xec\x84\x9c,\xea\xb3\xa0\xeb\x93\xb1\xed\x95\x99\xea\xb5\x90\xed\x95\x99\xec\x8a\xb5\xec\x84\x9c,\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90\xec\x9e\xac,\xec\x84\x9c\xec\xa0\x81,\xec\x8b\xa0\xeb\xac\xb8,\xec\x84\x9d\xec\x9c\xa0\xeb\xa5\x98,\xec\xb7\xa8\xec\x82\xac\xec\x9a\xa9LPG,\xeb\x93\xb1\xec\x9c\xa0,\xeb\xb6\x80\xed\x83\x84\xea\xb0\x80\xec\x8a\xa4,\xed\x9c\x98\xeb\xb0\x9c\xec\x9c\xa0,\xea\xb2\xbd\xec\x9c\xa0,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xec\x9a\xa9LPG,\xec\x9d\x98\xec\x95\xbd\xed\x92\x88,\xea\xb0\x90\xea\xb8\xb0\xec\x95\xbd,\xec\xa7\x84\xed\x86\xb5\xec\xa0\x9c,\xec\x86\x8c\xed\x99\x94\xec\xa0\x9c,\xec\x9c\x84\xec\x9e\xa5\xec\x95\xbd,\xec\xa7\x84\xed\x95\xb4\xea\xb1\xb0\xeb\x8b\xb4\xec\xa0\x9c,\xec\x86\x8c\xec\x97\xbc\xec\xa7\x84\xed\x86\xb5\xec\xa0\x9c,\xed\x94\xbc\xeb\xb6\x80\xec\xa7\x88\xed\x99\x98\xec\xa0\x9c,\xec\xb9\x98\xea\xb3\xbc\xea\xb5\xac\xea\xb0\x95\xec\x9a\xa9\xec\x95\xbd,\xec\xa1\xb0\xec\xa0\x9c\xec\x95\xbd,\xed\x95\x9c\xeb\xb0\xa9\xec\x95\xbd,\xeb\xb9\x84\xed\x83\x80\xeb\xaf\xbc\xec\xa0\x9c,\xeb\xb3\x91\xec\x9b\x90\xec\x95\xbd\xed\x92\x88,\xed\x99\x94\xec\x9e\xa5\xed\x92\x88,\xec\x83\xb4\xed\x91\xb8,\xeb\xb0\x94\xeb\x94\x94\xec\x9b\x8c\xec\x8b\x9c,\xea\xb8\xb0\xec\xb4\x88\xed\x99\x94\xec\x9e\xa5\xed\x92\x88,\xea\xb8\xb0\xeb\x8a\xa5\xec\x84\xb1\xed\x99\x94\xec\x9e\xa5\xed\x92\x88,\xec\x83\x89\xec\xa1\xb0\xed\x99\x94\xec\x9e\xa5\xed\x92\x88,\xeb\xaa\xa8\xeb\xb0\x9c\xec\x97\xbc\xec\x83\x89\xec\x95\xbd,\xea\xb8\xb0\xed\x83\x80,\xeb\x8b\xb4\xeb\xb0\xb0,\xec\x95\x84\xeb\x8f\x99\xed\x99\x94,\xea\xb5\xac\xeb\x91\x90,\xec\x9a\xb4\xeb\x8f\x99\xed\x99\x94,\xec\x8b\xa4\xeb\x82\xb4\xed\x99\x94,\xec\xa3\xbc\xed\x83\x9d\xec\x88\x98\xec\x84\xa0\xec\x9e\xac\xeb\xa3\x8c,\xec\x8b\x9d\xea\xb8\xb0,\xec\xbb\xb5,\xec\x86\xa5,\xed\x94\x84\xeb\x9d\xbc\xec\x9d\xb4\xed\x8c\xac,\xeb\x83\x84\xeb\xb9\x84,\xec\x88\x98\xec\xa0\x80,\xeb\xb0\x80\xed\x8f\x90\xec\x9a\xa9\xea\xb8\xb0,\xeb\xb6\x80\xec\x97\x8c\xec\x9a\xa9\xec\x9a\xa9\xea\xb5\xac,\xea\xb1\xb4\xec\xa0\x84\xec\xa7\x80,\xec\x86\x8c\xed\x98\x95\xea\xb0\x80\xec\x82\xac\xec\x9a\xa9\xed\x92\x88,\xec\x84\xb8\xed\x83\x81\xec\x84\xb8\xec\xa0\x9c,\xec\x84\xac\xec\x9c\xa0\xec\x9c\xa0\xec\x97\xb0\xec\xa0\x9c,\xec\xa0\x84\xea\xb5\xac,\xeb\xb6\x80\xec\x97\x8c\xec\x9a\xa9\xec\x84\xb8\xec\xa0\x9c,\xec\xb2\xad\xec\x86\x8c\xec\x9a\xa9\xec\x84\xb8\xec\xa0\x9c,\xec\x82\xb4\xec\xb6\xa9\xec\xa0\x9c,\xea\xb0\x80\xec\xa0\x95\xec\x9a\xa9\xeb\xb9\x84\xeb\x8b\x90\xec\x9a\xa9\xed\x92\x88,\xed\x82\xa4\xec\xb9\x9c\xed\x83\x80\xec\x9b\x94,\xeb\xb0\xa9\xed\x96\xa5\xec\xa0\x9c,\xec\x8a\xb5\xea\xb8\xb0\xec\xa0\x9c\xea\xb1\xb0\xec\xa0\x9c,\xec\xa2\x85\xec\x9d\xb4\xea\xb8\xb0\xec\xa0\x80\xea\xb7\x80,\xec\x83\x9d\xeb\xa6\xac\xeb\x8c\x80,\xeb\xa7\x88\xec\x8a\xa4\xed\x81\xac,\xeb\xb0\x98\xec\xb0\xbd\xea\xb3\xa0,\xec\x95\x88\xea\xb2\xbd,\xec\xbd\x98\xed\x83\x9d\xed\x8a\xb8\xeb\xa0\x8c\xec\xa6\x88,\xec\x9d\x98\xeb\xa3\x8c\xec\xb8\xa1\xec\xa0\x95\xea\xb8\xb0,\xeb\xb3\xb4\xec\xb2\xad\xea\xb8\xb0,\xec\xb9\x98\xeb\xa3\x8c\xec\x9e\xac\xeb\xa3\x8c,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xed\x83\x80\xec\x9d\xb4\xec\x96\xb4,\xec\xbb\xb4\xed\x93\xa8\xed\x84\xb0\xec\x86\x8c\xeb\xaa\xa8\xed\x92\x88,\xec\xa0\x80\xec\x9e\xa5\xec\x9e\xa5\xec\xb9\x98,\xec\x9e\xa5\xeb\x82\x9c\xea\xb0\x90,\xeb\xa0\x88\xec\xa0\x80\xec\x9a\xa9\xed\x92\x88,\xec\x9a\xb4\xeb\x8f\x99\xec\x9a\xa9\xed\x92\x88,\xec\x9b\x90\xec\x98\x88\xec\x9a\xa9\xed\x92\x88,\xeb\xb0\x98\xeb\xa0\xa4\xeb\x8f\x99\xeb\xac\xbc\xec\x9a\xa9\xed\x92\x88,\xec\xa2\x85\xec\x9d\xb4\xeb\xac\xb8\xea\xb5\xac,\xea\xb8\xb0\xed\x83\x80\xeb\xac\xb8\xea\xb5\xac,\xed\x95\x84\xea\xb8\xb0\xea\xb5\xac,\xed\x9a\x8c\xed\x99\x94\xec\x9a\xa9\xea\xb5\xac,\xec\xb9\xab\xec\x86\x94,\xec\xb9\x98\xec\x95\xbd,\xeb\xb9\x84\xeb\x88\x84,\xed\x99\x94\xec\x9e\xa5\xec\xa7\x80,\xea\xb5\xac\xea\xb0\x95\xec\x84\xb8\xec\xa0\x95\xec\xa0\x9c,\xea\xb0\x80\xeb\xb0\xa9,\xed\x95\xb8\xeb\x93\x9c\xeb\xb0\xb1,\xec\x9a\xb0\xec\x82\xb0,\xec\x9c\xa0\xeb\xaa\xa8\xec\xb0\xa8,\xec\x84\xa0\xea\xb8\x80\xeb\x9d\xbc\xec\x8a\xa4,\xec\xa7\x80\xea\xb0\x91,\xec\xa0\x84\xea\xb8\xb0 \xc2\xb7 \xea\xb0\x80\xec\x8a\xa4 \xc2\xb7 \xec\x88\x98\xeb\x8f\x84,\xec\xa0\x84\xea\xb8\xb0 \xc2\xb7 \xea\xb0\x80\xec\x8a\xa4 \xc2\xb7 \xec\x88\x98\xeb\x8f\x84,\xec\x83\x81\xec\x88\x98\xeb\x8f\x84\xeb\xa3\x8c,\xec\xa0\x84\xea\xb8\xb0\xeb\xa3\x8c,\xeb\x8f\x84\xec\x8b\x9c\xea\xb0\x80\xec\x8a\xa4,\xec\xa7\x80\xec\x97\xad\xeb\x82\x9c\xeb\xb0\xa9\xeb\xb9\x84,\xec\xa7\x91\xec\x84\xb8,\xec\xa7\x91\xec\x84\xb8,\xec\xa0\x84\xec\x84\xb8,\xec\x9b\x94\xec\x84\xb8,\xea\xb3\xb5\xea\xb3\xb5\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4,\xea\xb3\xb5\xea\xb3\xb5\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4,\xed\x95\x98\xec\x88\x98\xeb\x8f\x84\xeb\xa3\x8c,\xec\x93\xb0\xeb\xa0\x88\xea\xb8\xb0\xeb\xb4\x89\xed\x88\xac\xeb\xa3\x8c,\xec\xa0\x95\xed\x99\x94\xec\xa1\xb0\xec\xb2\xad\xec\x86\x8c\xeb\xa3\x8c,\xec\x99\xb8\xeb\x9e\x98\xec\xa7\x84\xeb\xa3\x8c\xeb\xb9\x84,\xed\x95\x9c\xeb\xb0\xa9\xec\xa7\x84\xeb\xa3\x8c\xeb\xb9\x84,\xec\x95\xbd\xea\xb5\xad\xec\xa1\xb0\xec\xa0\x9c\xeb\xa3\x8c,\xec\xb9\x98\xea\xb3\xbc\xec\xa7\x84\xeb\xa3\x8c\xeb\xb9\x84,\xec\x9e\x85\xec\x9b\x90\xec\xa7\x84\xeb\xa3\x8c\xeb\xb9\x84,\xeb\x8f\x84\xeb\xa1\x9c\xed\x86\xb5\xed\x96\x89\xeb\xa3\x8c,\xec\x97\xb4\xec\xb0\xa8\xeb\xa3\x8c,\xeb\x8f\x84\xec\x8b\x9c\xec\xb2\xa0\xeb\x8f\x84\xeb\xa3\x8c,\xec\x8b\x9c\xeb\x82\xb4\xeb\xb2\x84\xec\x8a\xa4\xeb\xa3\x8c,\xec\x8b\x9c\xec\x99\xb8\xeb\xb2\x84\xec\x8a\xa4\xeb\xa3\x8c,\xed\x83\x9d\xec\x8b\x9c\xeb\xa3\x8c,\xea\xb5\xad\xec\xa0\x9c\xed\x95\xad\xea\xb3\xb5\xeb\xa3\x8c,\xec\x9a\xb0\xed\x8e\xb8\xeb\xa3\x8c,\xec\x9c\xa0\xec\x84\xa0\xec\xa0\x84\xed\x99\x94\xeb\xa3\x8c,\xed\x9c\xb4\xeb\x8c\x80\xec\xa0\x84\xed\x99\x94\xeb\xa3\x8c,\xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xeb\xb0\xa9\xec\x86\xa1\xec\x88\x98\xec\x8b\xa0\xeb\xa3\x8c,\xec\x9c\xa0\xec\xb9\x98\xec\x9b\x90\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xea\xb5\xad\xea\xb3\xb5\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xec\x82\xac\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xea\xb5\xad\xea\xb3\xb5\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xec\x9b\x90\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xec\x82\xac\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xec\x9b\x90\xeb\x82\xa9\xec\x9e\x85\xea\xb8\x88,\xeb\xb3\xb4\xec\x9c\xa1\xec\x8b\x9c\xec\x84\xa4\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xec\x9a\x94\xec\x96\x91\xec\x8b\x9c\xec\x84\xa4\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xeb\xb6\x80\xeb\x8f\x99\xec\x82\xb0\xec\xa4\x91\xea\xb0\x9c\xec\x88\x98\xec\x88\x98\xeb\xa3\x8c,\xed\x96\x89\xec\xa0\x95\xec\x88\x98\xec\x88\x98\xeb\xa3\x8c,\xea\xb0\x9c\xec\x9d\xb8\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4,\xec\x99\xb8\xec\x8b\x9d,\xea\xb9\x80\xec\xb9\x98\xec\xb0\x8c\xea\xb0\x9c\xeb\xb0\xb1\xeb\xb0\x98,\xeb\x90\x9c\xec\x9e\xa5\xec\xb0\x8c\xea\xb0\x9c\xeb\xb0\xb1\xeb\xb0\x98,\xeb\xb9\x84\xeb\xb9\x94\xeb\xb0\xa5,\xec\x84\xa4\xeb\xa0\x81\xed\x83\x95,\xea\xb0\x88\xeb\xb9\x84\xed\x83\x95,\xec\x82\xbc\xea\xb3\x84\xed\x83\x95,\xed\x95\xb4\xeb\xac\xbc\xec\xb0\x9c,\xed\x95\xb4\xec\x9e\xa5\xea\xb5\xad,\xeb\xb6\x88\xea\xb3\xa0\xea\xb8\xb0,\xec\x87\xa0\xea\xb3\xa0\xea\xb8\xb0(\xec\x99\xb8\xec\x8b\x9d),\xeb\x8f\xbc\xec\xa7\x80\xea\xb0\x88\xeb\xb9\x84(\xec\x99\xb8\xec\x8b\x9d),\xec\x82\xbc\xea\xb2\xb9\xec\x82\xb4(\xec\x99\xb8\xec\x8b\x9d),\xec\x98\xa4\xeb\xa6\xac\xea\xb3\xa0\xea\xb8\xb0(\xec\x99\xb8\xec\x8b\x9d),\xeb\x83\x89\xeb\xa9\xb4,\xec\xb9\xbc\xea\xb5\xad\xec\x88\x98,\xec\xa3\xbd(\xec\x99\xb8\xec\x8b\x9d),\xec\x83\x9d\xec\x84\xa0\xec\xb4\x88\xeb\xb0\xa5,\xec\x83\x9d\xec\x84\xa0\xed\x9a\x8c(\xec\x99\xb8\xec\x8b\x9d),\xec\x9e\x90\xec\x9e\xa5\xeb\xa9\xb4,\xec\xa7\xac\xeb\xbd\x95,\xed\x83\x95\xec\x88\x98\xec\x9c\xa1,\xeb\xb3\xb6\xec\x9d\x8c\xeb\xb0\xa5,\xeb\x8f\x88\xea\xb0\x80\xec\x8a\xa4,\xec\x8a\xa4\xed\x85\x8c\xec\x9d\xb4\xed\x81\xac,\xec\x8a\xa4\xed\x8c\x8c\xea\xb2\x8c\xed\x8b\xb0,\xeb\x9d\xbc\xeb\xa9\xb4(\xec\x99\xb8\xec\x8b\x9d),\xea\xb9\x80\xeb\xb0\xa5,\xeb\x96\xa1\xeb\xb3\xb6\xec\x9d\xb4,\xec\xb9\x98\xed\x82\xa8,\xed\x96\x84\xeb\xb2\x84\xea\xb1\xb0,\xed\x94\xbc\xec\x9e\x90,\xec\x8c\x80\xea\xb5\xad\xec\x88\x98,\xec\xbb\xa4\xed\x94\xbc(\xec\x99\xb8\xec\x8b\x9d),\xea\xb8\xb0\xed\x83\x80\xec\x9d\x8c\xeb\xa3\x8c(\xec\x99\xb8\xec\x8b\x9d),\xec\x86\x8c\xec\xa3\xbc(\xec\x99\xb8\xec\x8b\x9d),\xeb\xa7\xa5\xec\xa3\xbc(\xec\x99\xb8\xec\x8b\x9d),\xeb\xa7\x89\xea\xb1\xb8\xeb\xa6\xac(\xec\x99\xb8\xec\x8b\x9d),\xea\xb5\xac\xeb\x82\xb4\xec\x8b\x9d\xeb\x8b\xb9\xec\x8b\x9d\xec\x82\xac\xeb\xb9\x84,\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd,\xec\x99\xb8\xec\x8b\x9d\xec\xa0\x9c\xec\x99\xb8,\xec\x9d\x98\xeb\xb3\xb5\xec\x88\x98\xec\x84\xa0\xeb\xa3\x8c,\xec\x84\xb8\xed\x83\x81\xeb\xa3\x8c,\xec\x84\xa4\xeb\xb9\x84\xec\x88\x98\xeb\xa6\xac\xeb\xb9\x84,\xea\xb3\xb5\xeb\x8f\x99\xec\xa3\xbc\xed\x83\x9d\xea\xb4\x80\xeb\xa6\xac\xeb\xb9\x84,\xea\xb0\x80\xec\xa0\x84\xec\xa0\x9c\xed\x92\x88\xec\x88\x98\xeb\xa6\xac\xeb\xb9\x84,\xea\xb0\x80\xec\xa0\x84\xec\xa0\x9c\xed\x92\x88\xeb\xa0\x8c\xed\x83\x88\xeb\xb9\x84,\xea\xb0\x80\xec\x82\xac\xeb\x8f\x84\xec\x9a\xb0\xeb\xaf\xb8\xeb\xa3\x8c,\xea\xb0\x84\xeb\xb3\x91\xeb\x8f\x84\xec\x9a\xb0\xeb\xaf\xb8\xeb\xa3\x8c,\xea\xb1\xb4\xea\xb0\x95\xea\xb8\xb0\xea\xb8\xb0\xeb\xa0\x8c\xed\x83\x88\xeb\xb9\x84,\xea\xb1\xb4\xea\xb0\x95\xea\xb2\x80\xec\xa7\x84\xeb\xb9\x84,\xec\xb9\x98\xea\xb3\xbc\xeb\xb3\xb4\xec\xb2\xa0\xeb\xa3\x8c,\xeb\xb3\x91\xec\x9b\x90\xea\xb2\x80\xec\x82\xac\xeb\xa3\x8c,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xec\x88\x98\xeb\xa6\xac\xeb\xb9\x84,\xec\x97\x94\xec\xa7\x84\xec\x98\xa4\xec\x9d\xbc\xea\xb5\x90\xec\xb2\xb4\xeb\xa3\x8c,\xec\x84\xb8\xec\xb0\xa8\xeb\xa3\x8c,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xed\x95\x99\xec\x9b\x90\xeb\xb9\x84,\xec\xa3\xbc\xec\xb0\xa8\xeb\xa3\x8c,\xec\x8a\xb9\xec\x9a\xa9\xec\xb0\xa8\xec\x9e\x84\xec\xb0\xa8\xeb\xa3\x8c,\xeb\x8c\x80\xeb\xa6\xac\xec\x9a\xb4\xec\xa0\x84\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xec\x9e\x90\xeb\x8f\x99\xec\xb0\xa8\xea\xb2\x80\xec\x82\xac\xeb\xa3\x8c,\xea\xb5\xad\xeb\x82\xb4\xed\x95\xad\xea\xb3\xb5\xeb\xa3\x8c,\xec\x97\xac\xea\xb0\x9d\xec\x84\xa0\xeb\xa3\x8c,\xec\x9d\xb4\xec\x82\xbf\xec\xa7\x90\xec\x9a\xb4\xec\x86\xa1\xeb\xa3\x8c,\xed\x83\x9d\xeb\xb0\xb0\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xed\x9c\xb4\xeb\x8c\x80\xec\xa0\x84\xed\x99\x94\xea\xb8\xb0\xec\x88\x98\xeb\xa6\xac\xeb\xb9\x84,\xec\xbb\xb4\xed\x93\xa8\xed\x84\xb0\xec\x88\x98\xeb\xa6\xac\xeb\xb9\x84,\xeb\xb0\x98\xeb\xa0\xa4\xeb\x8f\x99\xeb\xac\xbc\xea\xb4\x80\xeb\xa6\xac\xeb\xb9\x84,\xec\x88\x98\xec\x98\x81\xec\x9e\xa5\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xeb\xb3\xbc\xeb\xa7\x81\xec\x9e\xa5\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xed\x97\xac\xec\x8a\xa4\xed\x81\xb4\xeb\x9f\xbd\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xea\xb3\xa8\xed\x94\x84\xec\x97\xb0\xec\x8a\xb5\xec\x9e\xa5\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xea\xb3\xa8\xed\x94\x84\xec\x9e\xa5\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xeb\x8b\xb9\xea\xb5\xac\xec\x9e\xa5\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,\xeb\x85\xb8\xeb\x9e\x98\xeb\xb0\xa9\xec\x9d\xb4\xec\x9a\xa9\xeb\xa3\x8c,PC\xeb\xb0\xa9\xec\x9d\xb4

In [ ]:
df = pd.read_csv('consumer price index.csv')
df.head()

,시도별,시점,총지수,농축수산물,(농산물)곡물,쌀,현미,찹쌀,보리쌀,콩,...,이발료,미용료,뷰티미용료,산후조리원이용료,보험서비스료,자동차보험료,금융수수료,대입전형료,시험응시료,장례비
0,전국,1995,51.995,38.763,51.801,52.620,-,39.280,34.434,31.434,...,68.758,48.108,-,-,-,59.636,100.812,106.852,-,-
1,전국,1996,54.555,39.470,59.938,60.902,-,52.688,34.434,32.783,...,76.916,51.295,-,-,-,66.003,100.812,114.430,-,-
2,전국,1997,56.977,40.985,62.546,63.603,-,60.820,36.577,29.254,...,78.561,54.031,-,-,-,71.402,100.812,123.443,-,-
3,전국,1998,61.258,43.469,66.569,67.701,-,63.858,49.777,29.071,...,82.148,56.017,-,-,-,71.402,100.812,122.652,-,-
4,전국,1999,61.756,46.644,71.119,72.410,-,60.100,54.308,36.555,...,82.216,54.625,-,-,-,66.991,100.812,122.696,-,-

In [ ]:
df1 = df[['김', '단무지', '쌀', '당근', '달걀', '시금치', '김밥']] # 김밥에 필요한 재료들로만 다시 df1에 저장
df1.head()

        김     단무지       쌀      당근      달걀     시금치      김밥
0  39.820  48.897  52.620  32.909  40.896  26.185  44.996
1  39.399  52.324  60.902  37.604  40.033  33.370  46.961
2  39.821  53.126  63.603  37.357  42.048  36.844  48.165
3  46.739  54.593  67.701  39.231  50.002  38.009  51.206
4  47.340  58.379  72.410  35.136  46.318  36.134  50.632

# **[단계2] 데이터 전처리**

In [ ]:
!pip install koreanize-matplotlib # 한국어 사용

Collecting koreanize-matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl.metadata (992 bytes)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from koreanize-matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.17.0)
Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 59.5 MB/s eta 0:00:00
Installing collected packages: koreanize-matplotlib
Successfully installed koreanize-matplotlib-0.1.1

# **[단계3] 독립변수와 종속변수 설정하기**

# **[단계4] 데이터 쪼개기**

# **[단계5] 단순 선형회귀 모델 제작**

# **[단계6] 단순 선형회귀 모델 성능 평가**

# **[단계7] 다중 선형회귀 모델 제작**

# **[단계8] 다중 선형회귀 모델 성능 평가**

# **[단계9] 물가지수를 활용한 김밥 가격 예측하는 프로그램 모델 구현하기**